config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "mangos#index"

  # get 'mangos', to: 'mangos#index'
  # get 'mangos/:id', to: 'mangos#show'
  # get 'mangos/adicionar', to: 'mangos#new'
  # post 'mangos', to: 'mangos#create'

  resources :mangos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/mango.rb
class Mango < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/mangos_controller.rb
class MangosController < ApplicationController
  before_action :set_mango, only: [:show, :edit, :update, :destroy]

  def index
    @mangos = Mango.all
  end

  def show;  end

  def new
    @mango = Mango.new
  end

  def create
    @mango = Mango.new(params_mango)
    if @mango.save
      redirect_to mangos_url, notice: "Mango adicionado!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit;  end

  def update
    @mango = Mango.find(params[:id])
    if @mango.update(params_mango)
      redirect_to mango_path, notice: "Mango atualizado!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @mango = Mango.find(params[:id])
    if @mango.destroy
      redirect_to mangos_url, notice: "Mango apagado!"
    else
      redirect_to mango, notice: "Algo deu errado!"
    end
  end


  private
  def set_mango
    @mango = Mango.find(params[:id])
  end

  def params_mango
    params.require(:mango).permit(:descricao, :valor, :banco)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mangos_helper.rb
module MangosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MVC</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://kit.fontawesome.com/1ef87b5e1c.js" crossorigin="anonymous"></script>
  </head>

  <style>
    * {
      margin: 0;
      padding: 0;
    }

    nav {
      height: 50px;
      background-color: black;
      color: white;
      position: relative;
      display: flex;
      justify-content: end;
    }

    nav a {
      height: 40px;
      width: 40px;/*
      position: absolute;
      right: 20px;*/
      display: grid;
      place-items: center;
      margin: 5px;
      transition: background-color .5s;
      border-radius: 50px;
      text-decoration: none;
    }

    nav a:visited {
      color: white;
    }

    nav a:hover {
      background-color: white;
      color: black;
    }

  </style>

  <nav>

    <%# <%= link_to (new_mango_path) do %
      <i class="fa-solid fa-plus"></i>
    <% end %>

    <%= link_to (mangos_path) do%>
      <i class="fa-solid fa-house"></i>
    <% end %>
  </nav>

  <body>
    <%= yield %>
  </body>
</html>

app/views/mangos/_mango.html.erb
<style>
    .centraliza {
        margin: 3% 0;
        display: grid;
        place-items: center;
    }

    .centraliza2 {
        display: flex;
        flex-direction: column;
    }

    .back-btn a,
    .back-btn a:visited {
        color: black;
    }

    i {
        transform: scale(1.1);
        transition: ease-in-out .2s;
    }

    i:hover {
        transform: scale(1.2);
    }

    .form {
        padding: 20px 0;
        display: grid;
        place-items: center;
    }

    form {
        display: flex;
        flex-direction: column;
        width: 300px;
    }

    input {
        margin-bottom: 20px;
    }

    input {
        height: 20px;
    }

    input:last-child {
        height: 50px;
    }

</style>


<div class="centraliza">
    <div class="centraliza2">

        <div class="back-btn">
            <%= link_to (:back) do %>
                <i class="fa-solid fa-arrow-left"></i>
            <% end %>
        </div>

        <div class="form">
            <%= form_with(model: @mango) do |form| %>
                <%= form.label :Descrição %>
                <%= form.text_field :descricao %>

                <%= form.label :Valor %>
                <%= form.text_field :valor %>

                <%= form.label :Banco %>
                <%= form.text_field :banco %>

                <%= form.submit :'Salvar' %>
            <% end %>
        </div>

    </div>
</div>

app/views/mangos/edit.html.erb
<p style="color: green"><%= notice %></p>

<%= render 'mango' %>

app/views/mangos/index.html.erb
<style>
    table, td, th {
        border: 1px solid black;
        padding: 0 10px;
    }

    table {
        border-collapse: collapse;
    }

    th {
        height: 50px;
    }

    td {
        text-align: center;
    }

    tr:last-child {
        span: 3;
        border: 1px solid red;
    }

    .centraliza {
        margin: 3% 0;
        display: grid;
        place-items: center;
    }

    h1 {
        padding-bottom: 30px;
    }

    button,
    a,
    a:visited,
    a i {
        border: none;
        text-decoration: none;
        cursor: pointer;
        background-color: none;
        color: black;
        transform: scale(1);
        transition: ease-in-out .2s;
    }

    button {
        height: 100%;
        background-color: white;
    }

    button:hover,
    a i:hover {
        transform: scale(1.1);
    }
</style>


<div class="centraliza">
    <h1> Mangos! </h1>

    <p style="color: green"><%= notice %></p>
    <table>
        <tr>
            <th>Descrição</th>
            <th>Valor</th>
            <th> </th>
            <th> </th>
        </tr>

        <% @mangos.each do |mango| %>
        <tr>
            <td><%= mango.descricao%></td>
            <td><%= mango.valor%></td>
            <td>
                <%= link_to (mango) do %>
                    <i class="fa-solid fa-arrow-right"></i>
                <% end %>
            </td>
            <td>
                <%= button_to mango, method: :delete, form:{data:{turbo_confirm: 'Tem certeza que deseja apagar?'}} do %>
                    <i class="fa-solid fa-trash"></i>
                <% end %>
            </td>
        </tr>
        <% end %>

    </table>

    <%= link_to (new_mango_path) do %>
        <i class="fa-solid fa-plus" style="padding-top: 10px;"></i>
    <% end %>

</div>

app/views/mangos/new.html.erb
<%= render 'mango' %>

app/views/mangos/show.html.erb
<style>
    div {
        display: flex;
        flex-direction: row;
        padding-bottom: 20px;
    }

    p {
        font-weight: bold;
        padding-right: 5px;
    }

    .lado-a-lado {
        display: flex;
        justify-items: center;
        justify-content: space-between;
    }

    .centraliza {
        margin: 3% 0;
        display: grid;
        place-items: center;
    }

    .centraliza2 {
        display: flex;
        flex-direction: column;
    }

    button,
    a,
    a:visited {
        border: none;
        text-decoration: none;
        cursor: pointer;
        background-color: none;
        color: black;
    }

    button {
        height: 100%;
        background-color: white;
    }

    .lado-a-lado a,
    .lado-a-lado button {
        display: flex;
        flex-direction: row;
        text-decoration: none;
        color: black;
        transform: scale(1.1);
        transition: ease-in-out .2s;
    }

    .lado-a-lado a:hover,
    .lado-a-lado button:hover  {
        transform: scale(1.2);
    }
</style>

<div class="centraliza">
    <div class="centraliza2">
        <p style="color: green"><%= notice %></p>

        <div>
            <p>Descrição:</p>
            <%= @mango.descricao%>
        </div>

        <div>
            <p>Valor:</p>
            <%= @mango.valor%>
        </div>

        <div>
            <p>Banco:</p>
            <%= @mango.banco%>
        </div>

        <div>
            <p>Data de criação:</p>
            <%= @mango.created_at%>
        </div>

        <div>
            <p>Ultima atualização:</p>
            <%= @mango.updated_at%>
        </div>

        <div class="lado-a-lado">
            <%= link_to (mangos_path) do%>
                <i class="fa-solid fa-arrow-right fa-rotate-180"></i>
            <% end %>

            <%= link_to (edit_mango_path) do %>
                <i class="fa-solid fa-pen"></i>
            <% end %>

            <%= button_to @mango, method: :delete, form:{data:{turbo_confirm: 'Tem certeza que deseja apagar?'}} do %>
                <i class="fa-solid fa-trash"></i>
            <% end %>
        </div>
    </div>
</div>